# Generated by Django 3.1.5 on 2021-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210130_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='finish_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
