# Generated by Django 3.1.5 on 2021-01-31 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210130_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
