# Generated by Django 3.1.5 on 2021-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210131_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='PLZ',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
